"""add home_address to staff

Revision ID: 392cf67eb8f3
Revises: 4e25ef2fd31f
Create Date: 2026-06-25 20:10:59.694895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392cf67eb8f3'
down_revision: Union[str, None] = '4e25ef2fd31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('home_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'home_address')
    # ### end Alembic commands ###
