"""add_staff_model_and_student_fields

Revision ID: 4e25ef2fd31f
Revises: 0ed99263d767
Create Date: 2026-06-25 19:36:29.628854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e25ef2fd31f'
down_revision: Union[str, None] = '0ed99263d767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )

    # ── Data migration: copy existing users into staff ──
    from sqlalchemy import text
    conn = op.get_bind()
    conn.execute(text("""
        INSERT INTO staff (id, first_name, last_name, email, role, user_id, is_active, created_at, updated_at)
        SELECT
            gen_random_uuid(),
            COALESCE(SPLIT_PART(full_name, ' ', 1), 'Former'),
            COALESCE(NULLIF(SPLIT_PART(full_name, ' ', 2), ''), 'Staff'),
            email,
            role,
            id,
            is_active,
            NOW(),
            NOW()
        FROM users
        WHERE role IN ('teacher', 'hr', 'headmistress', 'admin', 'editor', 'viewer')
    """))

    # ── Set orphan teacher_id values to NULL before dropping constraints ──
    conn.execute(text("""
        UPDATE school_classes SET teacher_id = NULL
        WHERE teacher_id IS NOT NULL
        AND teacher_id NOT IN (SELECT id FROM users)
    """))
    conn.execute(text("""
        UPDATE class_subjects SET teacher_id = NULL
        WHERE teacher_id IS NOT NULL
        AND teacher_id NOT IN (SELECT id FROM users)
    """))

    # ── Drop old FK constraints before updating values ──
    fk_tasks = [
        ('school_classes', 'teacher_id', 'school_classes_teacher_id_fkey'),
        ('class_subjects', 'teacher_id', 'class_subjects_teacher_id_fkey'),
        ('attendance', 'recorded_by', 'attendance_recorded_by_fkey'),
        ('academic_records', 'recorded_by', 'academic_records_recorded_by_fkey'),
    ]
    for table, column, fk_name in fk_tasks:
        op.drop_constraint(fk_name, table, type_='foreignkey')

    # ── Update FK columns to point to staff.id ──
    for table, column, _ in fk_tasks:
        conn.execute(text(f"""
            UPDATE {table} t
            SET {column} = s.id
            FROM staff s
            WHERE s.user_id = t.{column}
        """))

    # ── Create new FK constraints to staff.id ──
    for table, column, _ in fk_tasks:
        op.create_foreign_key(None, table, 'staff', [column], ['id'])

    op.add_column('students', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('students', sa.Column('date_of_admission', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('home_address', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('parent_whatsapp', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('parent_relationship', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('emergency_contact', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('alt_emergency_contact', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('medical_conditions', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('blood_group', sa.String(length=5), nullable=True))
    conn.execute(text("UPDATE syllabus_topics SET term_id = (SELECT id FROM academic_terms ORDER BY is_active DESC, start_date DESC LIMIT 1) WHERE term_id IS NULL"))
    op.alter_column('syllabus_topics', 'term_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('syllabus_topics', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    conn.execute(text("UPDATE syllabus_topics SET is_completed = FALSE WHERE is_completed IS NULL"))
    op.alter_column('syllabus_topics', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_syllabus_topics_class_subject_id'), 'syllabus_topics', ['class_subject_id'], unique=False)
    op.drop_constraint('syllabus_topics_parent_id_fkey', 'syllabus_topics', type_='foreignkey')
    op.drop_constraint('syllabus_topics_class_subject_id_fkey', 'syllabus_topics', type_='foreignkey')
    op.drop_constraint('syllabus_topics_term_id_fkey', 'syllabus_topics', type_='foreignkey')
    op.create_foreign_key(None, 'syllabus_topics', 'syllabus_topics', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'syllabus_topics', 'academic_terms', ['term_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'syllabus_topics', 'class_subjects', ['class_subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('time_table_entries_class_id_fkey', 'time_table_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_table_entries', 'school_classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_table_entries', type_='foreignkey')
    op.create_foreign_key('time_table_entries_class_id_fkey', 'time_table_entries', 'school_classes', ['class_id'], ['id'])
    op.drop_constraint(None, 'syllabus_topics', type_='foreignkey')
    op.drop_constraint(None, 'syllabus_topics', type_='foreignkey')
    op.drop_constraint(None, 'syllabus_topics', type_='foreignkey')
    op.create_foreign_key('syllabus_topics_term_id_fkey', 'syllabus_topics', 'academic_terms', ['term_id'], ['id'])
    op.create_foreign_key('syllabus_topics_class_subject_id_fkey', 'syllabus_topics', 'class_subjects', ['class_subject_id'], ['id'])
    op.create_foreign_key('syllabus_topics_parent_id_fkey', 'syllabus_topics', 'syllabus_topics', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_syllabus_topics_class_subject_id'), table_name='syllabus_topics')
    op.alter_column('syllabus_topics', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('syllabus_topics', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('syllabus_topics', 'term_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('students', 'blood_group')
    op.drop_column('students', 'medical_conditions')
    op.drop_column('students', 'alt_emergency_contact')
    op.drop_column('students', 'emergency_contact')
    op.drop_column('students', 'parent_relationship')
    op.drop_column('students', 'parent_whatsapp')
    op.drop_column('students', 'home_address')
    op.drop_column('students', 'date_of_admission')
    op.drop_column('students', 'status')
    op.drop_column('students', 'middle_name')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.create_foreign_key('school_classes_teacher_id_fkey', 'school_classes', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key('class_subjects_teacher_id_fkey', 'class_subjects', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_recorded_by_fkey', 'attendance', 'users', ['recorded_by'], ['id'])
    op.drop_constraint(None, 'academic_records', type_='foreignkey')
    op.create_foreign_key('academic_records_recorded_by_fkey', 'academic_records', 'users', ['recorded_by'], ['id'])
    op.drop_table('staff')
    # ### end Alembic commands ###
