"""add passport_photo_url to students

Revision ID: 88a6507e1b73
Revises: 97a3766c1de3
Create Date: 2026-06-30 21:27:08.129622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a6507e1b73'
down_revision: Union[str, None] = '97a3766c1de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('passport_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'passport_photo_url')
    # ### end Alembic commands ###
